fix: make sure we could apply the getParent() method on confPath while it is a file name only.
❯ java -jar build/libs/solconfig.jar create default.json
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toFile()" because the return value of "java.nio.file.Path.getParent()" is null
	at com.solace.tools.solconfig.SempClient.freeMakerToString(SempClient.java:223)
	at com.solace.tools.solconfig.SempClient.readMapFromJsonFile(SempClient.java:211)
	at com.solace.tools.solconfig.Commander.getConfigBrokerFromFile(Commander.java:112)
	at com.solace.tools.solconfig.Commander.create(Commander.java:98)
	at com.solace.tools.solconfig.cli.CreateCommand.execute(CreateCommand.java:24)
	at com.solace.tools.solconfig.cli.SubCommand.call(SubCommand.java:15)
	at com.solace.tools.solconfig.cli.SubCommand.call(SubCommand.java:7)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.solace.tools.solconfig.App.main(App.java:11)